### ISSUE TITLE
f2e的e2e test呢

### ISSUE THREAD

**Issue by sky790312** [goodjack/developer-roadmap-chinese#1]
消失的e2e test
還有現在火紅的storybook

**Comment by goodjack** [comment]
這裡主要是翻譯原著
加上我對前端比較不熟
所以我也不知道為什麼沒有 😅

可以到  [kamranahmedse/developer-roadmap](https://github.com/kamranahmedse/developer-roadmap) 提供建議哦！

**Comment by sky790312** [comment]
haha 好唷 抱歉抱歉~~
