### ISSUE TITLE
Tips: ui-components framework learning for front-end 

### ISSUE THREAD

**Issue by Sidfate** [goodjack/developer-roadmap-chinese#10]
Maybe for front-enders, we always choose some ui-components frameworks, such as:

* element-ui
* ant-design
* semantic-ui

Learning to build common ui-components by ourselves is an important skill in my sight 😄 .

**Comment by goodjack** [comment]
This repository is a translation.

Please submit the issue to https://github.com/kamranahmedse/developer-roadmap
Thanks!

**Comment by goodjack** [comment]
https://github.com/kamranahmedse/developer-roadmap/issues/495
