### ISSUE TITLE
是否有相应的教程或书籍推荐？

### ISSUE THREAD

**Issue by faydanube** [goodjack/developer-roadmap-chinese#12]
非常感谢这么多年你的付出~~ 
已经工作八年，准备从头梳理一下自己的知识网络， 不知道是否有根据此路线图推荐教程的项目呢。

**Comment by goodjack** [comment]
感謝你的支持～
許多內容都可以在網路上找到
這裡我自己推薦兩個來源
- [Udemy](https://www.udemy.com) 
- [Laracasts](http://laracasts.com/)

另外哈佛的 [CS50](https://cs50.harvard.edu/) 課程也有不錯的基礎知識
提供你參考 😀
