### ISSUE TITLE
原著更新至 2021

### ISSUE THREAD

**Issue by flamerecca** [goodjack/developer-roadmap-chinese#15]
如果需要協助請不吝提出，或許可以一起來翻譯

**Comment by goodjack** [comment]
感謝 Recca 大！

主要是原著使用的軟體（[Balsamiq](https://balsamiq.com/)）
實在很難追蹤變化與修改既有內容

加上原著開始提供官方翻譯
以及現實生活忙碌等
種種逃避更新的理由 造成一直沒有發佈這裡的更新 😓

謝謝這個 issue，今天有點時間，來翻譯翻譯 ~~什麼叫驚喜~~

但還是很希望可以討論出如何解決 Balsamiq 煩人的問題。

**Comment by goodjack** [comment]
btw 我剛剛 push 了去年翻一半的內容... 😅
https://github.com/goodjack/developer-roadmap-chinese/tree/upgrade-to-2020

但我暫時沒有持續翻完 2020 版的計畫
目前就直上 2021 了

**Comment by goodjack** [comment]
已更新至 2021，謝謝大家 🎉
