### ISSUE TITLE
Graph Database中譯

### ISSUE THREAD

**Issue by cvdaystar** [goodjack/developer-roadmap-chinese#2]
或許翻成「圖資料庫」或直接維持原文比較貼切
https://en.wikipedia.org/wiki/Graph_database

儲存的應該是節點與節點間的關聯關係而非圖片喔

**Comment by goodjack** [comment]
感謝抓錯！馬上來改~

**Comment by goodjack** [comment]
最近發現台灣的用詞比較常出現 `圖形資料庫`
之後來改成這個用法（順便更新一下維基百科）。

**Comment by goodjack** [comment]
Closed by 81fc96c460e732bd8b495756767605de73ff7b58
