### ISSUE TITLE
我个人觉得前端这应该远远不够

### ISSUE THREAD

**Issue by iamike** [goodjack/developer-roadmap-chinese#4]
您确定你的图表中都包含了，我非常怀疑，我觉得试图用路线图的这种做法就像成年人扼杀小孩子画画的天赋，如果作者看过小王子，应该能明白我的意思，宇宙万物，何其复杂。
光CSS3这块, 类似这样的作品也可能永远不会出自中国的之手
http://matthew.wagerfield.com/parallax/
因为这背后 关于transform-style问题可能永远不会有人再去追问了
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-style
因为，我们太功利了，我们中国人是非常勤劳的民族，我从来不否认，但是，我们真的希望我们子女也这样学习知识？以具备市场竟争力？

我怀疑，我不想让自己的孩子走上这样一条路，我希望他能做自己喜欢的事，不要限制他的想像，不要试图给他灌输我们很自然的东西，即使那是真理，我也希望他能亲自去尝试，然后，挫折，沮丧，怀疑，然后，再告诉他我们这代人的解决方案。这样才不至于抹杀创新，创新意味着不按套路出牌，中国人加油，不要试图再总结这大千世界。要真正去改造这个世界，就意味着要推翻一些旧的东西。当然也包括那些我们不方便说的东西

**Comment by damody** [comment]
不衝突吧？ 有自己研究方向興趣的人根本沒什麼會來看這個，通常會來看這個的都是沒目標沒方向的新手。

**Comment by iamike** [comment]
问题就在这，您觉得没冲突的原因主要是因为您从事了可能相当长的一段时间的开发，这就像你在城市中待习惯了，您觉得从高速公路下来后，如果要去那，你就要从这走最近，因为所有人都从这走。当然，走这也许没错，但是，我觉得从深层次来讲，新人就会习惯于去走别人的人，不是吗？比特币，以太坊，tensorflow。。 中国找个智商245的也不难，但是，很少有自己开创的项目，您要说这些东西好，我当然也没时间一一去研究，但是，我不知道您可能会不会无意中改变多少人的平行空间，比如说，你将web网站开发分为了，前端，后端，和运维DevOps？三大类？这种思维逻辑是基于，长久以来，我们对WEB开发的总结，但是，这不代表将来？将来会是怎么样的？也许人工智能？将三者结合？那WEB开发是不是又变成了人工智能课题的一个分支？

**Comment by iamike** [comment]
未来的年青人也许根本不喜欢研究这些东西，他们也许会像我们看我们的前辈用机器语言编写一样看待今天的我们

**Comment by FlandreDaisuki** [comment]
學校不應該教中文，中文是長久以來我們對中文使用的總結，但是這不代表將來目前使用中文的地區還會使用中文。或許未來這些地區會使用更有效率的語言，使用中文會鉗制這些孩子的思想。

學校不應該教數學，數學是長久以來世界對「數」這個概念的總結，但不代表這個概念不會被推翻。未來可能使用更高階更抽象的概念來包含或相容這個概念，我們教數學會鉗制孩子未來的想像。

(下略)
- - -
你說的理想有一部分我同意，但我認為該學的基礎還是要學。

有基礎，遇到問題，了解問題，才有機會去解決問題。

**Comment by iamike** [comment]
我不知道大家有没有同感，我们这所以有WEB前端开发，很大程度上是因为我们现在猎取信息方式是屏幕时代，但是将来未必都是屏幕，也许以后都不用手机了，怎么办？大家一起失业？

**Comment by DCTmaybe1201** [comment]
如果你覺得不夠，那就提供你覺得應該要在上面的內容發個pr，而不只是講一些看起來很有道理但對這個project沒有任何幫助的話

**Comment by HappyHackingNinja** [comment]
這是給已經知道想走 Web 開發的求知者們，避免誤走歪路的建議指南。而 Machine Learning 與 Blockchain 這些最近被炒熱的技術，似乎與 Roadmap 上的項目並不衝突，Roadmap 上的項目是現代開發人員應該要知道的知識，而路線的最後也提醒**繼續探索**嘗試創新結合新的技術。至於未來會怎麼發展誰都很難說個準，與其要瞎子摸象臆測未來發展，不如把握當下先把基礎準備好吧

@goodjack 我覺得這個 Issue 可以關了

**Comment by goodjack** [comment]
原本想說開著 issue 可以看到更多觀點，但其實關掉也是可以繼續討論啦 😅

以我的觀點，這個 repo 的目的應該不是限制該學什麼，而是在指引方向。
尤其是對想踏入 Web 開發領域的工程師來說，能夠在毫無頭緒該怎麼前進時給予一盞明燈。
技術不停的推陳出新，也總有新的觀點和需求出現，持續學習與探索才是提升自己水準和價值的來源。

再次說明，這裡是翻譯 repo，如果對內容有建議或想法也歡迎到原 repo 提出建言哦 😄
