### ISSUE TITLE
请问 roadmap 图片中使用的是哪个字体？

### ISSUE THREAD

**Issue by jxlwqq** [goodjack/developer-roadmap-chinese#5]
请问 roadmap 图片中使用的是哪个字体？
我想 fork 这个项目，使用简体中文翻译下。
————————
請問 roadmap 圖片中使用的是哪個字體？
我想 fork 這個項目，使用簡體中文翻譯下。

**Comment by goodjack** [comment]
使用 Balsamiq 開啟檔案就有指定英文字體了
中文的部分是 macOS 預設字體，我猜是蘋方

不過簡體中文版已經有一些人翻譯了呢
- https://github.com/z-jingjie/developer-roadmap-zh-CN
- https://github.com/ccloli/developer-roadmap-zh-CN

**Comment by jxlwqq** [comment]
谢谢。
之前买了 Balsamiq，一直没怎么用，借这个翻译的机会，刚好练习练习。

**Comment by goodjack** [comment]
我都是用網頁版的試用版 (掩面

**Comment by jxlwqq** [comment]
简体中文版，我翻译 Banner 图，随便做了一个繁体版本。你需要吗？

![banner_1](https://user-images.githubusercontent.com/2421068/43937157-8e6a0862-9c8e-11e8-866d-91e2d9182324.png)

**Comment by goodjack** [comment]
好啊
你要不要開一個 PR 呢
可以留個紀錄感謝你的貢獻

**Comment by jxlwqq** [comment]
@goodjack 同学，#7
