### ISSUE TITLE
About Simplified Chinese version

### ISSUE THREAD

**Issue by Encounter77** [goodjack/developer-roadmap-chinese#9]
你好，我是一名做开发的实习生，看了你翻译的台湾中文版本的这个学习路线图，有些地方因为是繁体，想做一个简体中文版的web学习路线图，不知作者的意下如何呢？

**Comment by goodjack** [comment]
嗨你好，簡體中文版已經有一些人翻譯了呢！

在這裡優先推薦本專案貢獻者 @jxlwqq 的延伸專案：
- https://github.com/jxlwqq/developer-roadmap-chinese

也有其他的專案可以參考：
- https://github.com/z-jingjie/developer-roadmap-zh-CN
- https://github.com/ccloli/developer-roadmap-zh-CN

希望有幫助到你～
